#!/usr/bin/env python3
"""
monitor_disks.py

Monitors block devices and when a new disk is connected checks its size.
If the disk is larger than a threshold (default 10 TB) the script will:
 - wipe the disk once with random data
 - create a single NTFS partition using the entire disk
 - print the disk's SMART data (smartctl -a)

This script is destructive. It requires root and the --force flag to actually
perform the wipe and repartitioning. Without --force it will perform a dry-run
and only log the actions it would take.

Dependencies (commands invoked by the script):
 - lsblk
 - parted
 - mkfs.ntfs (from ntfs-3g / ntfsprogs)
 - smartctl (from smartmontools)
 - dd (or shred if available) for wiping
 - partprobe or partx (optional, script tries several ways to notify kernel)

Usage examples:
  sudo ./monitor_disks.py --interval 5 --threshold 10T        # dry-run (no --force)
  sudo ./monitor_disks.py --force                            # perform destructive actions

Author: Generated by Copilot CLI runtime in VS Code (AI assistant)
"""

import argparse
import json
import logging
import os
import shlex
import signal
import subprocess
import sys
import time
import concurrent.futures
import threading
from typing import Dict, Set, Optional, List

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
log = logging.getLogger("monitor_disks")

# Helpers

def run(cmd, check=True, capture_output=False):
    log.debug("Running: %s", cmd)
    return subprocess.run(cmd, shell=True, check=check, capture_output=capture_output, text=True)


def is_root():
    return os.geteuid() == 0


def human_to_bytes(s: str) -> int:
    # Accept formats like 10T, 100G, or raw integer bytes
    s = s.strip().upper()
    units = {"K": 1024, "M": 1024 ** 2, "G": 1024 ** 3, "T": 1024 ** 4, "P": 1024 ** 5}
    if s[-1] in units:
        try:
            return int(float(s[:-1]) * units[s[-1]])
        except Exception:
            raise ValueError(f"Invalid size: {s}")
    return int(s)


def probe_block_devices() -> Dict[str, dict]:
    """Return a dict of kname -> device info for top-level block devices (type == disk)."""
    try:
        # Include mountpoint and fstype so we can detect mounted partitions and filesystems
        res = run("lsblk -J -b -o NAME,KNAME,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE", capture_output=True)
    except subprocess.CalledProcessError as e:
        log.error("Failed to run lsblk: %s", e)
        return {}
    data = json.loads(res.stdout)
    out = {}
    for dev in data.get("blockdevices", []):
        if dev.get("type") == "disk":
            kname = dev.get("kname")
            out[kname] = dev
    return out


def get_device_path(kname: str) -> str:
    return f"/dev/{kname}"


def device_size_bytes(dev) -> int:
    # lsblk already gave size in bytes
    try:
        return int(dev.get("size", 0))
    except Exception:
        return 0


def get_smart_serial(device: str) -> Optional[str]:
    """Return the device serial number as reported by smartctl -i, or None if not found."""
    try:
        res = run(f"smartctl -i {shlex.quote(device)}", check=False, capture_output=True)
        out = res.stdout or ""
        for line in out.splitlines():
            if "Serial Number" in line:
                parts = line.split(":", 1)
                if len(parts) == 2:
                    return parts[1].strip()
    except Exception:
        pass
    return None


def print_smart(device: str, kname: Optional[str] = None, out_dir: Optional[str] = None) -> Optional[str]:
    """Run smartctl -a on device, log to stdout and save output to a timestamped file.

    Filename uses the last 6 characters of the device serial number (if available) as a prefix,
    otherwise falls back to the kernel name (kname) or device basename. Files are saved in the
    script's root/smartreports directory by default.

    Returns the filepath written, or None if the file was not written.
    """
    log.info("Attempting to get SMART data for %s", device)
    try:
        # determine output directory: script root/smartreports if not provided
        if not out_dir:
            script_root = os.path.dirname(os.path.abspath(__file__))
            out_dir = os.path.join(script_root, "smartreports")

        can_write = True
        try:
            os.makedirs(out_dir, exist_ok=True)
        except Exception as e:
            log.error("Failed to create SMART reports directory %s: %s", out_dir, e)
            can_write = False

        serial = get_smart_serial(device)
        prefix = None
        if serial:
            prefix = serial[-6:]
        elif kname:
            prefix = kname
        else:
            prefix = os.path.basename(device)

        # sanitize prefix for filename
        safe_prefix = ''.join(c if (c.isalnum() or c in '-_') else '_' for c in prefix)

        timestamp = time.strftime("%Y%m%d-%H%M%S")
        filename = f"{safe_prefix}_{timestamp}.smart.txt"
        filepath = os.path.join(out_dir, filename) if can_write else None

        # Run smartctl -a and capture output
        res = run(f"smartctl -a {shlex.quote(device)}", check=False, capture_output=True)
        out_text = (res.stdout or "") + (res.stderr or "")

        if can_write and filepath:
            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(out_text)
                log.info("SMART output for %s written to %s", device, filepath)
            except Exception as e:
                log.error("Failed to write SMART output to %s: %s", filepath, e)
                filepath = None
        else:
            log.warning("SMART output not saved to file because %s is not writable", out_dir)
            filepath = None

        # Also stream smartctl output to log for immediate visibility
        for line in out_text.splitlines():
            log.info("[SMART %s] %s", safe_prefix, line)

        return filepath
    except Exception as e:
        log.error("smartctl failed: %s", e)
        return None


def notify_kernel(device: str):
    # try partprobe, then partx, then udevadm settle
    try:
        run(f"partprobe {shlex.quote(device)}", check=False)
    except Exception:
        pass
    try:
        run(f"partx -u {shlex.quote(device)}", check=False)
    except Exception:
        pass
    try:
        run("udevadm settle", check=False)
    except Exception:
        pass


def has_zfs_label(device: str) -> bool:
    """Detect whether the raw device contains ZFS labels/metadata.

    Methods (in order):
    - zdb -l /dev/DEVICE (preferred if zdb available)
    - blkid check for TYPE=zfs_member
    - quick strings search for 'ZFS' marker
    """
    # Try zdb -l
    try:
        res = run(f"zdb -l {shlex.quote(device)}", check=False, capture_output=True)
        out = (res.stdout or "") + (res.stderr or "")
        # zdb -l prints pool name and other label info when present
        if out and ("name" in out.lower() or "pool" in out.lower() or "zfs" in out.lower()):
            return True
    except Exception:
        pass
    # Try blkid
    try:
        res = run(f"blkid {shlex.quote(device)}", check=False, capture_output=True)
        out = (res.stdout or "") + (res.stderr or "")
        if out and "TYPE=\"zfs_member\"" in out:
            return True
    except Exception:
        pass
    # Quick strings scan of the start of device
    try:
        # read first 1MB and search for ZFS
        res = run(f"dd if={shlex.quote(device)} bs=512 count=2048 status=none | strings | grep -i ZFS", check=False, capture_output=True)
        out = (res.stdout or "") + (res.stderr or "")
        if out.strip():
            return True
    except Exception:
        pass
    return False


def clear_zfs_labels(device: str, progress_prefix: str = ""):
    """Attempt to clear ZFS labels using zpool labelclear -f. Falls back to wipefs -a if zpool not available."""
    # Preferred: zpool labelclear -f /dev/device
    try:
        run_stream(f"zpool labelclear -f {shlex.quote(device)}", prefix=progress_prefix or device, check=True)
        return
    except subprocess.CalledProcessError:
        log.warning("%szpool labelclear failed or zpool not present; falling back to wipefs", progress_prefix)
    # Fallback
    try:
        run_stream(f"wipefs -a {shlex.quote(device)}", prefix=progress_prefix or device, check=True)
    except subprocess.CalledProcessError as e:
        log.error("%sFailed to clear ZFS labels with wipefs: %s", progress_prefix, e)
        raise


def run_stream(cmd: str, prefix: str = "", check: bool = True):
    """Run a shell command and stream combined stdout/stderr to the logger line-by-line.
    Lines are prefixed with `prefix` when provided to help identify per-device output.
    Raises CalledProcessError if check is True and the process exits non-zero.
    """
    log.debug("Running (stream): %s", cmd)
    proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    try:
        if proc.stdout is not None:
            for line in proc.stdout:
                line = line.rstrip()
                if prefix:
                    log.info("[%s] %s", prefix, line)
                else:
                    log.info("%s", line)
        ret = proc.wait()
        if check and ret != 0:
            raise subprocess.CalledProcessError(ret, cmd)
    except Exception:
        try:
            proc.kill()
        except Exception:
            pass
        proc.wait()
        raise


def alarm_sound():
    """Play a simple terminal bell and attempt to use a system sound player if available."""
    try:
        sys.stdout.write("\a")
        sys.stdout.flush()
    except Exception:
        pass
    # Try aplay or paplay if present
    player = shutil_which("aplay") or shutil_which("paplay")
    if player:
        try:
            run(f"{player} /usr/share/sounds/alsa/Front_Center.wav", check=False)
        except Exception:
            pass


def wipe_disk(device: str, dry_run: bool, progress_prefix: str = ""):
    """Wipe a device with one pass of random data, using a tuned dd invocation by default
    to maximize throughput. Attempts the fastest method first and falls back if necessary.
    """
    if dry_run:
        log.info("%sDry-run: would wipe %s once with random data", progress_prefix, device)
        return
    log.info("%sWiping %s with one pass of random data using tuned dd (bs=64M, oflag=direct). This may take a very long time.", progress_prefix, device)

    # Primary: tuned dd with large block size and direct I/O
    dd_cmd_direct = f"dd if=/dev/urandom of={shlex.quote(device)} bs=64M status=progress oflag=direct conv=fdatasync"
    try:
        run_stream(dd_cmd_direct, prefix=progress_prefix or device, check=True)
        return
    except subprocess.CalledProcessError as e:
        log.warning("%sTuned dd with oflag=direct failed: %s; retrying without oflag=direct", progress_prefix, e)

    # Secondary: tuned dd without direct I/O
    dd_cmd = f"dd if=/dev/urandom of={shlex.quote(device)} bs=64M status=progress conv=fdatasync"
    try:
        run_stream(dd_cmd, prefix=progress_prefix or device, check=True)
        return
    except subprocess.CalledProcessError as e:
        log.warning("%sTuned dd without oflag failed: %s; falling back to shred or smaller dd", progress_prefix, e)

    # Tertiary: try shred if present (one pass)
    shred_path = shutil_which("shred")
    if shred_path:
        cmd = f"shred -v -n 1 {shlex.quote(device)}"
        try:
            run_stream(cmd, prefix=progress_prefix or device, check=True)
            return
        except subprocess.CalledProcessError as e:
            log.warning("%sshred failed: %s; attempting final dd fallback", progress_prefix, e)

    # Final fallback: dd with smaller block size
    final_cmd = f"dd if=/dev/urandom of={shlex.quote(device)} bs=4M status=progress conv=fdatasync"
    try:
        run_stream(final_cmd, prefix=progress_prefix or device, check=True)
        return
    except subprocess.CalledProcessError as e:
        log.error("%sAll wipe methods failed: %s", progress_prefix, e)
        raise


def shutil_which(cmd: str) -> Optional[str]:
    # simple which implementation
    for path in os.environ.get("PATH", "").split(":"):
        p = os.path.join(path, cmd)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    return None


def get_by_ids_for_kname(kname: str) -> List[str]:
    """Return a list of /dev/disk/by-id entries (full paths) that point to /dev/{kname}.
    If /dev/disk/by-id is missing or empty, returns an empty list.
    """
    byid_dir = "/dev/disk/by-id"
    target = f"/dev/{kname}"
    out: List[str] = []
    try:
        if not os.path.isdir(byid_dir):
            return out
        for name in os.listdir(byid_dir):
            full = os.path.join(byid_dir, name)
            try:
                if os.path.islink(full):
                    # os.path.realpath resolves the symlink to an absolute path
                    real = os.path.realpath(full)
                    if real == target:
                        out.append(full)
            except Exception:
                continue
    except Exception:
        pass
    return out


def device_has_mounts(devinfo: dict) -> bool:
    """Return True if the device or any of its partitions have mountpoints."""
    try:
        if devinfo.get('mountpoint'):
            return True
        for child in devinfo.get('children', []) or []:
            if child.get('mountpoint'):
                return True
    except Exception:
        pass
    return False


def create_ntfs_partition(device: str, dry_run: bool, progress_prefix: str = ""):
    # Create GPT label and a single partition that spans the disk, then mkfs.ntfs
    if dry_run:
        log.info("%sDry-run: would create GPT and single NTFS partition on %s", progress_prefix, device)
        return
    log.info("%sCreating GPT label and single NTFS partition on %s", progress_prefix, device)
    # Wipe partition table signatures first (safety)
    try:
        run_stream(f"wipefs -a {shlex.quote(device)}", prefix=progress_prefix or device, check=False)
    except Exception:
        pass
    # parted: create gpt and mkpart
    try:
        run_stream(f"parted -s {shlex.quote(device)} mklabel gpt mkpart primary 0% 100%", prefix=progress_prefix or device, check=True)
    except subprocess.CalledProcessError as e:
        log.error("%sparted failed: %s", progress_prefix, e)
        raise
    notify_kernel(device)
    part1 = device + "1"
    # Wait for partition node to appear
    for i in range(10):
        if os.path.exists(part1):
            break
        time.sleep(1)
    if not os.path.exists(part1):
        log.warning("%sPartition node %s did not appear; attempting partprobe and continuing", progress_prefix, part1)
        notify_kernel(device)
        time.sleep(2)
    # Format as NTFS
    mkfs = shutil_which("mkfs.ntfs") or shutil_which("mkntfs")
    if not mkfs:
        log.error("%smkfs.ntfs (ntfs-3g/mkntfs) not found in PATH; cannot create NTFS filesystem", progress_prefix)
        raise RuntimeError("mkfs.ntfs not found")
    try:
        run_stream(f"{shlex.quote(mkfs)} -F -L wiped {shlex.quote(part1)}", prefix=progress_prefix or device, check=True)
    except subprocess.CalledProcessError as e:
        log.error("%smkfs.ntfs failed: %s", progress_prefix, e)
        raise


def handle_new_disk(kname: str, devinfo: dict, threshold_bytes: int, do_force: bool, alarm: bool = False, initial_by_ids: Optional[List[str]] = None, zfs_action: str = 'skip'):
    """Handle a newly-detected disk. Uses /dev/disk/by-id entries (if available) to verify identity before destructive actions.

    initial_by_ids: list of by-id symlink paths captured at detection time. If provided, the function
    verifies that the current by-id entries for the device still overlap with initial_by_ids before proceeding.
    """
    device = get_device_path(kname)
    size = device_size_bytes(devinfo)
    prefix = kname  # short prefix for logging
    log.info("[%s] Detected new disk (size=%d bytes) at %s", prefix, size, device)
    if size < threshold_bytes:
        log.info("[%s] Disk is below threshold (%d bytes); skipping", prefix, threshold_bytes)
        return
    dry_run = not do_force
    log.info("[%s] Disk exceeds threshold (%d bytes). dry_run=%s", prefix, threshold_bytes, dry_run)

    # Identity verification using /dev/disk/by-id
    try:
        current_by_ids = get_by_ids_for_kname(kname)
    except Exception:
        current_by_ids = []
    if initial_by_ids:
        # If we captured by-id entries when the device was first seen, ensure they still match
        if not current_by_ids or not set(current_by_ids).intersection(set(initial_by_ids)):
            log.error("[%s] Device identity mismatch: by-id entries changed. initial=%s current=%s. Aborting to avoid accidental operation.",
                      prefix, initial_by_ids, current_by_ids)
            return
        else:
            log.info("[%s] by-id verification passed: %s", prefix, current_by_ids)
    else:
        if not current_by_ids:
            log.warning("[%s] No /dev/disk/by-id entries found for device; proceeding but identity is less robust.", prefix)
        else:
            log.info("[%s] Found by-id entries: %s", prefix, current_by_ids)

    # ZFS detection and handling
    try:
        zfs_present = has_zfs_label(device)
    except Exception:
        zfs_present = False
    if zfs_present:
        log.info("[%s] ZFS label detected on device %s", prefix, device)
        if zfs_action == 'skip':
            log.info("[%s] Skipping device with ZFS label (config zfs_action=skip). To clear labels: use --zfs-action clear or run 'zpool labelclear -f %s' manually.", prefix, device)
            return
        elif zfs_action == 'clear':
            log.info("[%s] Clearing ZFS labels on %s as requested by zfs_action=clear", prefix, device)
            try:
                clear_zfs_labels(device, progress_prefix=f"[{prefix}]")
            except Exception as e:
                log.error("[%s] Failed to clear ZFS labels: %s", prefix, e)
                return
    else:
        log.debug("[%s] No ZFS label detected on %s", prefix, device)

    # Re-check device existence
    if not os.path.exists(device):
        log.error("[%s] Device node %s no longer exists; aborting", prefix, device)
        return

    # Print SMART data before any destructive operations (useful)
    smart_file = print_smart(device, kname=prefix)

    # If device appears to be mounted (or has mounted partitions), do not perform destructive actions.
    try:
        if device_has_mounts(devinfo):
            log.info("[%s] Device or partitions appear mounted; saving SMART report but skipping destructive operations. Unmount all partitions to allow wiping.", prefix)
            return
    except Exception:
        pass

    # Ensure the SMART file was actually written before proceeding to destructive work
    if not dry_run:
        if not smart_file or not os.path.exists(smart_file):
            log.error("[%s] SMART report was not saved to file (%s); aborting to avoid accidental operation.", prefix, smart_file)
            return
    # Wipe once with random data
    wipe_disk(device, dry_run=dry_run, progress_prefix=f"[{prefix}]")
    # Create NTFS partition and format
    create_ntfs_partition(device, dry_run=dry_run, progress_prefix=f"[{prefix}]")
    # Print SMART data after operations
    print_smart(device, kname=prefix)
    if alarm:
        log.info("[%s] Operations complete; sounding alarm", prefix)
        alarm_sound()


def main():
    parser = argparse.ArgumentParser(description="Monitor new block disks and optionally wipe/repartition large disks")
    parser.add_argument("--threshold", default="10T", help="Size threshold; e.g. 10T, 500G, or bytes. Default: 10T")
    parser.add_argument("--interval", type=float, default=5.0, help="Polling interval in seconds (default 5)")
    parser.add_argument("--force", action="store_true", help="Perform destructive actions (wiping and repartitioning). Without this flag the script runs in dry-run mode")
    parser.add_argument("--concurrency", type=int, default=1, help="Number of disks to process concurrently (default 1 = sequential)")
    parser.add_argument("--alarm", action="store_true", help="Play an alert sound when each disk finishes processing")
    parser.add_argument("--zfs-action", choices=["skip","clear"], default="skip",
                        help="How to handle disks with existing ZFS labels: skip (default) or clear (destructive)")
    parser.add_argument("--log-level", default="INFO", help="Logging level")
    args = parser.parse_args()

    numeric_level = getattr(logging, args.log_level.upper(), None)
    if not isinstance(numeric_level, int):
        raise ValueError("Invalid log level")
    logging.getLogger().setLevel(numeric_level)

    # Interactive numeric menu for quick selection when running in a terminal.
    def ask_number(prompt: str, default: str) -> str:
        try:
            resp = input(f"{prompt} [{default}]: ")
            if not resp.strip():
                return default
            return resp.strip()
        except EOFError:
            return default

    # If running interactively (TTY) and no explicit CLI overrides were provided (defaults), offer a quick numeric menu.
    # This is intended for fast, interactive churn workflows.
    if sys.stdin.isatty():
        log.info("Interactive terminal detected. Offering quick selection menu (press Enter to accept defaults).")
        # Mode: dry-run vs destructive
        mode = ask_number("1) Mode: 1=Dry-run (safe), 2=Destructive (wipe & format)", "1")
        if mode == "2":
            args.force = True
        else:
            args.force = False
        # Concurrency
        conc = ask_number("2) Concurrency: number of disks to process concurrently", str(args.concurrency))
        try:
            args.concurrency = max(1, int(conc))
        except Exception:
            args.concurrency = 1
        # ZFS action
        zfs_choice = ask_number("3) ZFS handling: 1=skip ZFS devices (safe), 2=clear ZFS labels (destructive)", "1")
        args.zfs_action = 'clear' if zfs_choice == '2' else 'skip'
        # Alarm
        alarm_choice = ask_number("4) Alarm on completion: 1=no, 2=yes", "2" )
        args.alarm = True if alarm_choice == '2' else False
        # Interval
        interval_choice = ask_number("5) Poll interval in seconds", str(args.interval))
        try:
            args.interval = float(interval_choice)
        except Exception:
            args.interval = args.interval
        log.info("Selected: force=%s, concurrency=%d, zfs_action=%s, alarm=%s, interval=%.1fs",
                 args.force, args.concurrency, args.zfs_action, args.alarm, args.interval)

    if not is_root():
        log.error("This script must be run as root (sudo). Exiting.")
        sys.exit(2)

    try:
        threshold_bytes = human_to_bytes(args.threshold)
    except ValueError as e:
        log.error("Invalid threshold: %s", e)
        sys.exit(2)

    log.info("Starting disk monitor. threshold=%d bytes (%.2f TiB). interval=%.1fs. force=%s",
             threshold_bytes, threshold_bytes / (1024.0 ** 4), args.interval, args.force)

    # track seen devices with initial metadata including by-id entries
    seen_details: Dict[str, dict] = {}

    def handle_sigterm(signum, frame):
        log.info("Received termination signal; exiting")
        sys.exit(0)

    signal.signal(signal.SIGINT, handle_sigterm)
    signal.signal(signal.SIGTERM, handle_sigterm)

    # Executor for optional concurrency
    executor = None
    if args.concurrency and args.concurrency > 1:
        log.info("Using ThreadPoolExecutor with max_workers=%d", args.concurrency)
        executor = concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency)

    def _task(k, info, initial_by_ids, zfs_action):
        try:
            handle_new_disk(k, info, threshold_bytes, args.force, alarm=args.alarm, initial_by_ids=initial_by_ids, zfs_action=zfs_action)
        except Exception as e:
            log.exception("Failed to handle new disk %s: %s", k, e)

    def submit_task(k, info, initial_by_ids, zfs_action):
        if executor:
            # submit to thread pool and don't block here
            executor.submit(_task, k, info, initial_by_ids, zfs_action)
        else:
            _task(k, info, initial_by_ids, zfs_action)

    # initial population: capture existing devices and process them as well
    devices = probe_block_devices()
    for k, info in devices.items():
        by_ids = get_by_ids_for_kname(k)
        seen_details[k] = {"info": info, "by_ids": by_ids}
        # Submit existing device for processing (mounted devices will be detected and handled safely)
        submit_task(k, info, by_ids, args.zfs_action)

    try:
        while True:
            try:
                devices = probe_block_devices()
                for k, info in devices.items():
                    if k not in seen_details:
                        # new disk
                        by_ids = get_by_ids_for_kname(k)
                        seen_details[k] = {"info": info, "by_ids": by_ids}
                        submit_task(k, info, by_ids, args.zfs_action)
                # Remove devices that disappeared from seen to allow re-processing if re-added
                removed = set()
                for s in list(seen_details.keys()):
                    if s not in devices:
                        removed.add(s)
                if removed:
                    log.debug("Devices removed since last check: %s", ",".join(removed))
                    for r in removed:
                        seen_details.pop(r, None)
                time.sleep(args.interval)
            except Exception:
                log.exception("Error in monitoring loop; sleeping and continuing")
                time.sleep(args.interval)
    finally:
        if executor:
            try:
                executor.shutdown(wait=False)
            except Exception:
                pass


if __name__ == '__main__':
    main()
